module ErrorReporting

using Printf
using ..Evaluate

export report_errors

"""
    report_errors(prob_full::Dict, ttns, subset_keys; prob_precision=6, ...)

Print per-key error statistics comparing a TTNS model to reference probabilities.

The function compares the probabilities generated by `ttns` against the reference `prob_full`.
The analysis is split between keys provided in `subset_keys` (the "kept" set) and those
in `prob_full` but not in `subset_keys` (the "dropped" set).
"""
function report_errors(prob_full::Dict, ttns, subset_keys::Union{AbstractSet, AbstractVector};
                       prob_precision::Int=6, rel_precision::Int=4, sum_precision::Int=12,
                       print_sections::Bool=true)
  kept_keys = sort!(collect(subset_keys))
  dropped_keys = sort!(setdiff(collect(keys(prob_full)), kept_keys))

  function analyze_section(keys, title)
    errors = Float64[]
    sum_reference = 0.0
    sum_recovered = 0.0
    if print_sections
      println(title)
      if isempty(keys)
        println("  (no entries)")
        return errors
      end
      @printf("  %-15s %-15s %-15s %s\n", "p_reference", "p_model", "rel_error", "key")
    elseif isempty(keys)
      return errors
    end

    for x_input in keys
      p_reference = prob_full[x_input]
      p_model = evaluate(ttns, x_input)
      rel_error = p_reference == 0 ? (p_model == 0 ? 0.0 : Inf) : abs(p_reference - p_model) / p_reference
      push!(errors, rel_error)
      sum_reference += p_reference
      sum_recovered += p_model
      if print_sections
        @printf("  %-15.*f %-15.*f %-15.*e %s\n",
                prob_precision, p_reference,
                prob_precision, p_model,
                rel_precision, rel_error,
                string(x_input))
      end
    end
    if print_sections
      @printf("  Sum reference: %.*f\n", sum_precision, sum_reference)
      @printf("  Sum recovered: %.*f\n", sum_precision, sum_recovered)
    end
    return errors
  end

  kept_errors = analyze_section(kept_keys, "Errors for keys included in reconstruction")
  if print_sections
    println()
  end
  dropped_errors = analyze_section(dropped_keys, "Errors for keys omitted from reconstruction")

  all_errors = vcat(kept_errors, dropped_errors)

  stats = function(errors)
    if isempty(errors)
      return (mean=NaN, max=NaN, variance=NaN, std=NaN)
    end
    mean_error = sum(abs.(errors)) / length(errors)
    max_error = maximum(abs.(errors))
    variance_error = sum((abs(err) - mean_error)^2 for err in errors) / length(errors)
    std_error = sqrt(variance_error)
    return (mean=mean_error, max=max_error, variance=variance_error, std=std_error)
  end

  return (
    overall = stats(all_errors),
    kept = stats(kept_errors),
    dropped = stats(dropped_errors),
  )
end

end
